### ISSUE TITLE
Node/observer could not start v1.0.89

### ISSUE THREAD

**Issue by soringp** [ElrondNetwork/elrond-go#1170]
One of my validators must have been missed on the latest snapshot, and when starting as Observer I get this error:

INFO [2020-02-28 15:03:17.169] starting as observer node
ERROR[2020-02-28 15:03:17.170] option DestinationShardAsObserver is not set in config.toml

![image](https://user-images.githubusercontent.com/16723548/75561567-e6d73080-5a4f-11ea-8f3f-148610aaec8c.png)

The option is missing from the config:

![image](https://user-images.githubusercontent.com/16723548/75561193-454fdf00-5a4f-11ea-805a-606823d53d09.png)

**Comment by iulianpascalau** [comment]
Right, thanks for the heads-up. The problem raised because the option was moved from config.toml to prefs.toml and the scripts v2 does not touch prefs.toml file. Reinstalling the app will fix the issue but a manual fix needs to be done in order to not reinstall elrond-go.
in prefs.toml, the following option needs to be added at the end of the file:
```
   # DestinationShardAsObserver represents the desired shard when running as observer
   # value will be given as string. For example: "0", "1", "15", "metachain"
   DestinationShardAsObserver = "0"
```

We will fix the error message as to not provide misleading information.

**Comment by iulianpascalau** [comment]
fixed error messages https://github.com/ElrondNetwork/elrond-go/pull/1171

**Comment by soringp** [comment]
Adding the config section to prefs.toml solves the problem.

Thanks!
