### ISSUE TITLE
Number of transaction in pool showing zero except meta

### ISSUE THREAD

**Issue by victoroshi** [ElrondNetwork/elrond-go#1352]
All shards except meta are showing transaction in pool = 0 as shown in the screenshot below
![image](https://user-images.githubusercontent.com/7301249/78459747-072f8600-76b3-11ea-8bd0-78e1dd6519df.png)

![image](https://user-images.githubusercontent.com/7301249/78459775-5bd30100-76b3-11ea-871b-cde5205a1a40.png)

Reward estimation and total reward in ERD has been **0.00** for all the shards for a very long time. I thought this new fix all address that

**Comment by elronscam8** [comment]
ERD/Elrond Scam Coin. Team ERD is a con man. Don't buy ERD. I send this
 message every day to everyone in the group. Prevent more people from being conned by sharing with you.
  ERD BIG DUMP SELL NOW ...

**Comment by miiu96** [comment]
Hello thank you for the feedback. 
1. Shard nodes display 0 transactions in pool because maybe all the transactions was processed. And on the metachain node is displayed the number of shard headers that are in pool.
2. For problem with rewards estimation it is normal to be 0 because right now mechanism that estimate rewards is disabled.

**Comment by iulianpascalau** [comment]
Rewards should be 0 for now as the estimator is turned off. Will be removed from the termui window. @mihaib79

**Comment by raduchis** [comment]
fixed
