### ISSUE TITLE
node does not recognize validator key after reboot

### ISSUE THREAD

**Issue by ravenx29** [ElrondNetwork/elrond-go#1473]
I have restarted my vps wich has 4 nodes, all of them are like this now:
![image](https://user-images.githubusercontent.com/26198807/80286177-91a75a80-8732-11ea-851c-99be1e7ed32d.png)
but the new key is it at the right place
![image](https://user-images.githubusercontent.com/26198807/80286229-cca98e00-8732-11ea-9ca6-5606476e87c9.png)

**Comment by ravenx29** [comment]
hope this helps also:
![image](https://user-images.githubusercontent.com/26198807/80287229-15fcdc00-8739-11ea-8429-fbebaef95214.png)

**Comment by iulianpascalau** [comment]
There were some issues displaying the termui window. This is caused by not refreshing correctly on the first run. In about 20 seconds it should refresh itself and the issue from the first picture should not appear afterwards. Regarding the second issue, there was a bug in bootstrap storer that was fixed. Reference PR #1497
