### ISSUE TITLE
[QUESTION] - doEndRoundJobByParticipant.CommitBlock Warning

### ISSUE THREAD

**Issue by arcsoft-ro** [ElrondNetwork/elrond-go#1891]
Following the release of v1.0.127 the following warning message started to occur in the logs:

Jun  9 06:10:36 erd7 node[137571]: #033[0;33mWARN #033[0m[2020-06-09 03:10:36.467]   doEndRoundJobByParticipant.CommitBlock   #033[0;33melapsed time#033[0m = 1.025493213s

Please investigate if this may cause further issues.

**Comment by bogdan-rosianu** [comment]
Hello!
That log message is displayed when the `CommitBlock` function takes longer than 1 second.
Do you have a full log from when this happened?
@SebastianMarian maybe you can help with investigating.

**Comment by SebastianMarian** [comment]
Actually these logs has been intentionally added to track this part of code. We want to be sure that everything works as expected in our protocol. Probably the value which has been used for this Warn is a little bit lower, 2 seconds would be more reasonable and probably would be changed in the following patches/PRs. Although some isolated stumbles could happen from time to time ( > 2 sec), considering that the node is interacting with storage in every round, what is important is that these situations to not come up too often and theirs values to be still reasonable. There was some cases when we observed values with two digits in terms of seconds there, and we "blamed" the compaction mechanism or other stuff which happen in the levelDB library from time to time, but we want to be sure that the problem is not in our protocol, so this is why this Warn messages will be kept there for a while.
