### ISSUE TITLE
[BUG] - shardProcessor.createMiniBlocks Error in node logs

### ISSUE THREAD

**Issue by arcsoft-ro** [ElrondNetwork/elrond-go#1892]
The following error occured in the logs for the nodes that are part of Shard0 and Shard1. It did not occur on the nodes part of metachain.

Jun  9 10:41:18 erd6 node[180293]: #033[0;33mWARN #033[0m[2020-06-09 07:41:18.030]   shardProcessor.createMiniBlocks          #033[0;33merror#033[0m = shard is stuck #033[0;33mshard#033[0m = 4294967295

<details>
<summary>Executing details</summary>
<pre>
Application version string: v1.0.127-0-g07a688e4d
Hosting VPS: private 
</pre>
</details>

**Comment by sasurobert** [comment]
This is not a critical bug, in case the metachain stopped notarizing some of the shard headers, or the other shard is slow in processing the previous cross shard miniblocks the leader will skip adding new transactions to the block, as it considers that the destination shard has too much to work on, better add those transactions later. In today's case (BoN) the problem is that metachain consensus is slow - thus all of the shards consider they need to take it slow for now, until metachain catches up.

**Comment by arcsoft-ro** [comment]
Thanks for the details on this Robert. I will then close this one
