### ISSUE TITLE
Keystore file cant be uploaded on mobile device

### ISSUE THREAD

**Issue by CryptoChaser13** [ElrondNetwork/elrond-go#1938]
I have setup my node using a laptop. I have made a wallet first at wallet.elrond.com and have downloaded the keystore file of my wallet.

I tried to recover my wallet on my android device and download the keystore file again so i can access it on either devices. But as i try to access the wallet on my mobile using the keystore file, the file wont be uploaded.

**Comment by arhtudormorar** [comment]
Hi & thanks for your feedback!
  Can you please let us know that mobile device you are using and what steps would bee needed to reproduce the error?
  I assume you have done the following:
1. Create a wallet by pressing the Create Wallet button and saving the secret pharse
2. On mobile, access https://wallet.elrond.com/recover and enter the secret words in the correct order
3. Save the new generated keystore file on the device
4. Try to access the wallet with the new keystore file (using the latest set password) but with no success

  Can you please provide a printscreen of the last step? Is there an error message on the https://wallet.elrond.com/unlock/keystore page?

**Comment by LucianMincu** [comment]
Hi @CryptoChaser13!

It's been a while since we haven't got any feedback on this issue. 
Please let us know if the new releases have covered and solved your issue. 

If not, kindly follow up on our previous instructions and we'll make sure to come back with an update right away. 

Thanks!

**Comment by Aydin-** [comment]
I'm having a similar problem.

On mobile (IOS 14.2):
- Using Maiar browser the keystore file does not even download, no matter how many times I retry.
- Using Chrome the file is downloaded successfully but then I cannot select the file in order to access my wallet

On MacBook:
- Chrome: cannot select keystore file, dragging and dropping it does nothing.
- Firefox: same probl.. 

oh..

So, I just figured it out, I needed to rename the keystore file with a .json extension. It had been simply named "document" by Chrome. 

Even when I was able to select the "document" file before, it was being ignored for not having a .json extension.
