### ISSUE TITLE
[BUG] Rating issue: Maybe it's calculated wrong

### ISSUE THREAD

**Issue by anhnd** [ElrondNetwork/elrond-go#1949]
When playing around with the rating data I see something weird: I checked nodes on the top ten and basically what I saw is node with better performance had lower rating as you can see below. They both had the same totalNumLeaderSuccess, the node at 7th place performed better in validator role but had lower rating.

4th place: :"fa4170a5a97a413b69f8823859c153b954e49ce3aeaa046652c057d747315092ebc6bc96baf8d34daa415de7c0bffa0ce0529277988f1e22cd78d05b00aebff7d2a7d82fa5707224d1d7f0f9600fdbb590377bff886adb82428cddbca27eb395":{"tempRating":51.5134,"numLeaderSuccess":0,"numLeaderFailure":0,"numValidatorSuccess":1,"numValidatorFailure":0,"rating":51.50973,"ratingModifier":1,"totalNumLeaderSuccess":5,"totalNumLeaderFailure":0,"totalNumValidatorSuccess":62,"totalNumValidatorFailure":34,"shardId":1,"validatorStatus":"eligible"}

7th place: "1c66fc6162889832ddbe406a5090a036d34d56083fdfba85896b106bd52d9580ee56cb6aac76135272c22fa95fba4a04a763c247edcd1ffd16f0cc3c47177f4b64dc26893b6f66147e8d2dd132fb6af481af0026c2f3b711a54c4420dc11bc8e":{"tempRating":51.476658,"numLeaderSuccess":0,"numLeaderFailure":0,"numValidatorSuccess":1,"numValidatorFailure":0,"rating":51.47299,"ratingModifier":1,"totalNumLeaderSuccess":5,"totalNumLeaderFailure":0,"totalNumValidatorSuccess":102,"totalNumValidatorFailure":4,"shardId":0,"validatorStatus":"eligible"}

<details>
<summary>Executing details</summary>
I got the data from the explorer and from https://api.elrond.com/validator/statistics
<pre>
Application version string: Nodes in the network were running at version 1.0.131
Hosting VPS: not related 
</pre>
</details>

**Comment by raduchis** [comment]
The problem here was that the totalNumValidatorFailure takes into consideration 2 different things: 
1. the block was not proposed and all had their ratings decreased.
2. the block was proposed and correct, but the signature of the current validator was not among the 2/3+1 signatures in the block. here the rating is actually increased.

The rating computation is correct but it is not actually easy visible/computable from the outside.

Thanks for the sugggestion!
