### ISSUE TITLE
add wait list time when shuffling-out restart until it's done and run for minimum 1 minutes to prevent down time that can result in jailing [FEAT]

### ISSUE THREAD

**Issue by scraido** [ElrondNetwork/elrond-go#2041]
I need this feature because it can rate our node correctly instead of what happen with case #2037, it also can help with good specs vps but with low bandwidth ex. vultr 4 TB/month equals 12.17 Mbit/s sustained

so when it's become shuffling, it should be on waiting list node while it restart until run, then the uptime start count after it run for 30"sec - 60"sec

**Comment by LucianMincu** [comment]
Hi @scraido! 

The current implementation puts by default all the shuffled nodes into the waiting list first in order the be able to sync the current state and only after 1 epoch it will be moved to the eligible list. 
In the current state of the testnet, 1 epoch = 1 hour which sets the difficulty 12x or 24x higher as in will be at mainnet stage where the epoch will be set to 12 or 24 hours and therefore one node after reshuffle will have up to 24x more time to sync.
Also the sync problem is amplified because of the current network throttling applied by the hosting providers for most of the network validators run by the community and where you should be able to sync from. 

I hope this clarify the current state of the implementation as I can understand it already covers your request! 👍

**Comment by scraido** [comment]
thank you for the explanation, i'm sorry because of this bug it disguises the function that actually already exists :)
