### ISSUE TITLE
Cannot change the node's Rest API Port at runtime

### ISSUE THREAD

**Issue by soringp** [ElrondNetwork/elrond-go#244]
The Rest API port seems to be hardcoded in main.go with the name "rest-api-port", and requires rebuilding the app after it's changed. Please expose it either in config.toml or as an argument when starting the node over CLI.

Thanks

**Comment by LucianMincu** [comment]
Hi @soringp! 

the Rest API port is already exposed at runtime with the following **-rest-api-port**
Example: `./node -rest-api-port 8081`

Also you can use `./node --h` for listing all available Node CLI flags. 
The output should look like this:
`NAME:
   Elrond Node CLI App - This is the entry point for starting a new Elrond node - the app will start after the genesis timestamp
USAGE:
   node [global options]

AUTHOR:
   The Elrond Team <contact@elrond.com>

GLOBAL OPTIONS:
   --genesis-file value              The node will extract bootstrapping info from the genesis.json (default: "./config/genesis.json")
   --nodesSetup-file value           The node will extract initial nodes info from the nodesSetup.json (default: "./config/nodesSetup.json")
   --port value                      Port number on which the application will start (default: 0)
   --config value                    The main configuration file to load (default: "./config/config.toml")
   --p2pconfig value                 The configuration file for P2P (default: "./config/p2p.toml")
   --tx-sign-sk value                Private key that the node will load on startup and will sign transactions - temporary until we have a wallet that can do that
   --sk value                        Private key that the node will load on startup and will sign blocks
   --profile-mode value              Profiling mode. Available options: cpu, mem, mutex, block
   --tx-sign-sk-index value          Single sign private key index specifies the 0-th based index of the private key to be used from initialBalancesSk.pem file. (default: 0)
   --sk-index value                  Private key index specifies the 0-th based index of the private key to be used from initialNodesSk.pem file. (default: 0)
   --num-of-nodes value              Number of nodes specifies the maximum number of nodes which will be used from initialNodes list exposed in nodesSetup.json file (default: 18446744073709551615)
   --storage-cleanup                 If set the node will start from scratch, otherwise it starts from the last state stored on disk
   --initialBalancesSkPemFile value  The file containing the secret keys which ... (default: "./config/initialBalancesSk.pem")
   --initialNodesSkPemFile value     The file containing the secret keys which ... (default: "./config/initialNodesSk.pem")
   --gops-enable                     Enables gops over the process. Stack can be viewed by calling 'gops stack <pid>'
   --serversconfig value             The configuration file for servers confidential data (default: "./config/servers.toml")
   --rest-api-port value             The port on which the rest API will start on (default: "8080")
   --boostrap-round-index value      Boostrap round index specifies the round index from which node should bootstrap from storage (default: 4294967295)
   --help, -h                        show help
   --version, -v                     print the version

VERSION:
   v1.0.4`

Thanks!

**Comment by soringp** [comment]
You're right, I see it now, I'll give it a try :) Thanks!
