### ISSUE TITLE
Endless "Time is Out" Looping

### ISSUE THREAD

**Issue by joesixpack** [ElrondNetwork/elrond-go#256]
"Time is out" errors is endlessly happening after upgrading to v1.07.  It happens whether or not the db is wiped.  Logs:

[observer.zip](https://github.com/ElrondNetwork/elrond-go/files/3365466/observer.zip)
[validator.zip](https://github.com/ElrondNetwork/elrond-go/files/3365467/validator.zip)

**Comment by joesixpack** [comment]
Here's the log for an observer that only had a few time is outs but bootstrapped successfully.

[observer2.zip](https://github.com/ElrondNetwork/elrond-go/files/3365492/observer2.zip)

**Comment by SebastianMarian** [comment]
"Time is out" is just a warning message that says that some requested data has not been received in some given time. It's not a real error. It will requested again and again until it will received it from some randomly selected peers for each new request. Anyway, I will investigate now the first log to see if there is something different which caused the endlessly requests.

**Comment by soringp** [comment]
My validator node on 1.0.7 is stuck on time out, and I've restarted it a few times. Something is wrong because the size of transactions folder is at 1.6gb, while an observer on the same shard but running on branch 248 is at 5.6gb.

[1fbc7a0835b9-2019-07-07-23-44-15.zip](https://github.com/ElrondNetwork/elrond-go/files/3367841/1fbc7a0835b9-2019-07-07-23-44-15.zip)

**Comment by iulianpascalau** [comment]
Related to #248
