### ISSUE TITLE
[FEAT] Proper failover for validator nodes

### ISSUE THREAD

**Issue by ank-everstake** [ElrondNetwork/elrond-go#2725]
In continuing of our chat and calls we open this issue to centralize communication and gather feedback.

Recently we have been making some intensive testing to make automatic failover scripts for our validator nodes. We didn't change the default config and used official deploy scheme (scripts).

As we use large powerful baremetal server to handle the load we wanted to make a hot-standby mirror for our main server with 20 nodes.
At first we tried to launch all 20 nodes at once. But it hangs even on the largest Scaleway VM (GP1-XL) with 48 cores and 256GB RAM.
We changed to sequentially launch the nodes in packs of 2 with 10 minute intervals. There was nearly 100% CPU utilization even with 2 nodes. 

Main points:
> Is there any limitation for a p2p layer for 1 IP address?

Are you referring running multiple nodes on the same host? In that case the answer is no, libp2p does not have such limitations. You can run as many nodes as you want on the same host. The only limitation is done by the operating system for the max opened files and connections (please check ulimit configuration)

>Can we make a snapshot from an active node and import the DB datadir with rsync to another? From our testing it seems possible, but is it supported?

Yes, you can copy any db from another node from a specific shard and place it to the other validator node that is assigned to that shard. Both processes should be done while the binary is stopped, in order to prevent DB corruption. All Validator DBs does only contain shard specific data, but not node specific data.

>Are there any possible optimizations for getting faster sync times? 

Initial load is high as the node checks each block for 2 epochs. More CPU cores, or maintain DB for each shard to spawn faster with it. 

On call we have ended up that there are some variants:

- maintaining a pool of observers (from 4 to total number of your nodes) in each shard and migrating validator keys on one of them individually in case of failure. Good only if you have 2-3 nodes max.

- maintain one small-sized instance with observers in each shard. Make an Ansible role(or any other script that help to spin up the node) that rsync's node DB from ready-made shard data from needed shard on observer. Deploy is made to instance large enough to handle usual load of your main node.  In this case the initial sync is faster. Error prone as server(instance) ordering can be eventually long enough for rating drop seriously, DB export problems, deploying the server with ansible can break with each upgrade of the node and needs testing after each upgrade of the node and scripts.

- make "main validator / following (backup) node" scheme with realization in the source code and official support as a feature from Elrond team. Keys are deployed on both nodes, but the follower node doesn't make blocks and only follows changing shards. Making blocks starts only on manual restart with a flag like `sign_blocks=true`. This will speed up the failover in case the main node will fail. Best variant from every perspective. Static infrastructure, always ready to run with minimal downtime.

Currently the main failover solution obviously is to deploy nodes separately on different servers to mitigate risks having everything on one server.

**Comment by flyingbasalt** [comment]
Very interested in this. A fourth variant could be a mix of your first and third bullet points: "main validator / following (backup) node" scheme but with the backup nodes running as observers on their own keys while each syncing to the destination shard of the validator they would replace. 

This could be configured by specifying the block sign public key of the validator in the `prefs.toml` of its corresponding backup observer, e.g. with `DestinationShardAsObserver = "follow <pubkey>"` so that the observer can calculate the destination shard of the validator.

The benefit of this scheme is that it leaves up to the operator whether to keep the actual validator key on the failover machine at all times, or only move it there when the failover gets triggered. A command line flag `sign_blocks=false` could still be useful as an extra safety against double signing from inadvertently starting the backup with the validator keys, e.g. if replacing the validator key with the observer key failed for some reason when the main outage is solved and the failover is swithched back to follower.

Another benefit of keeping the always-online followers run on their own observer keys is that the status of both the validators and their followers is always easily monitored on the explorer and heartbeat, instead of one of the two randomly masking the other at any given time.

**Comment by iulianpascalau** [comment]
We have conducted a meeting in which we agreed that the fail-over feature will be implemented. The initial discussion focused on the following key aspects:
1. The elrond-go node will be able to start as an observer but will keep track of the shard movement of a provided BLS public key. In this way the observer (let's call it failover-observer) will switch shards in the same manner as the validator with the said public key will do.
2. The failover-observer will have a defined config parameter that will specify how many consensus rounds are allowed to be skipped by the main validator machine before it will automatically turn on the consensus signing mechanism (and that BLS public key will produce valid signatures and blocks). If the main validator machine will start producing blocks again, the failover-observer will stop signing/producing blocks imediately.
3. If that parameter will be configured to a high value (say 1000000), then the feature number 2. will be essentially turned off. 

In this way we can satisfy both the community and the above mentioned requirements by having a built-in automatic fail-over mechanism and a way for that automatic mechanism to be easily turned off, leaving the observer machine always ready with the required data for the provided BLS key.

**Comment by iulianpascalau** [comment]
Implementation is done and now is in the review and testing phase. Related to #2817.

**Comment by iulianpascalau** [comment]
After reviewing the implementation and having a few responses to the questions asked, I can conclude the following:
The redundancy mechanism won't rely on having 1 main node as a validator and all backup nodes as observes because that implementation would have impacted larger section of production code. Instead, we will run n validators with the almost the same configuration and **the same validatorKey.pem file**. The difference between configurations consists on an option inside the prefs.toml file.
That configuration option called `RedundancyLevel` can be used as following:
- a `0` value will represent that the node is the main validator.
The value `0` will be the default, if the option is missing (as we do not re-write the prefs.toml files during the node's upgrade) will still make that node the main validator: backwards compatibility holds.
- a positive value will represent the "order of the back-up node" in the automatic fail-over sequence. Example: let's suppose we have 3 nodes running with the same key. One with the redundancy level set to 0, one with 1 and one with 3. The node with level 0 will propose and sign upon blocks. The other 2 will sync (and shuffle out) but will not sign anything. If the main validator fails, the backup validator with level 1 will start producing/signing blocks after level*5 missed rounds. So, after a 5 missed rounds by the main validator, the backup node with level 1 will take the turn. Now, if the backup node 1 is down, the second backup node will start producing/signing blocks after 3*5 = 15 rounds after the main validator failed and 10 rounds after the failed backup node 1 should have been produced a block.
- a large value for this level option (say 1 million) will mean that the backup observers won't get the chance to produce/sign blocks but will sync with the network and shuffle out just as the main validator will behave.

**Comment by ank-everstake** [comment]
Maybe it would be more safe to make `RedundancyLevel` be allowed to disable the failover feature by setting to `-1`.
Like explicit safe value.

**Comment by iulianpascalau** [comment]
Implemented #2817 and #2833. The first PR implements the feature requests. The later implements the following feature: the backup nodes will advertise on the network a different public key (autogenerated at startup) and thus, concealing the real public key that will be used when signing the header blocks. This was done because of 2 reasons: 
1. the backup node(s) will not cause BLS signature re-verification when idle
2. it slightly prevents DDoS attacks as an attacker can not find all IPs behind a targeted BLS public key: when an attacker takes down the main host, the backup nodes will advertise the public key when they will start signing blocks.

Will provide info when testing will be possible on the testnet and then close this issue.

**Comment by iulianpascalau** [comment]
The redundancy feature request is now part of the binary starting from v1.1.32 and up. Will close this issue. Thanks for the support! :+1:
