### ISSUE TITLE
[BUG] (not urgent) configuration mixes ntp servers with different leap second behaviors

### ISSUE THREAD

**Issue by flyingbasalt** [ElrondNetwork/elrond-go#2743]
Assuming half second error is significant with 6 seconds rounds: `config.toml` lists time servers from Google, Cloudflare and Apple. These treat UTC leap seconds in different ways, which can slowly nudge different nodes up to half a second apart from each other during the 24 hours around a leap second.

- Google smears the leap second over 24 hours centered on the midnight leap second: https://developers.google.com/time/smear

- Cloudshare, like the public pool.ntp.org servers, use the standard NTP way of flagging an impending leap second: https://developers.cloudflare.com/time-services/ntp/usage

- As to Apple, I can't find for sure what they do with leap seconds

Google's smear is deterministic and documented so it could be undone (https://github.com/google/unsmear), or it may be good enough to just avoid using time.google.com in the 24 hours around a leap second. https://github.com/beevik/ntp makes the impending [leap indicator](https://tools.ietf.org/html/rfc5905#section-7.3) available. 

An alternate source of time could be the NTP Pool Project with an elrond vendor zone (https://www.ntppool.org/en/vendors.html). Unfortunately some parts of the world don't have very many active servers: https://www.ntppool.org 

This is not at all urgent. The earliest dates the next leap second might occur are midnight on 31 Dec. 2021 and 30 June 2022, and they are officially announced months in advance at ftp://hpiers.obspm.fr/iers/bul/bulc/bulletinc.dat

**Comment by SebastianMarian** [comment]
Actually there isn't a real problem with the leap second because of the following:

1. All nodes use the same order for these servers, Hosts = ["time.google.com", "time.cloudflare.com",  "time.apple.com"], so even in the leap second situation they all take the same NTP value from google. So they will have the same timestamp at the beginning of each round.
2. Assuming that some of the nodes will have trouble syncing with google and will do this with cloudflare or apple, they will have an offset for maximum ~1h, after which, they will start syncing again taking the servers in the same order, starting with google.
3. Beside this, we have a protection if the current synced value is lower/higher than a threshold compared with the last/old value synced, and so, the node will ignore the current synced value and will keep the last one, until the next sync time will come (~1h)

Taking into consideration the above mentions, I don't think that this would be a real problem, so I think that is not necessary to remove google from the list not even to move it at the end of the servers list.
