### ISSUE TITLE
Can not connect to elrond Node

### ISSUE THREAD

**Issue by Wangmmx** [ElrondNetwork/elrond-go#2758]
I set up and run a node locally, and it worked normally before. Recently, an error occurred suddenly:
`{ StatusCodeError: 500 - {"data":null,"error":"sending request error","code":"internal_issue"}`, and I could't connect to it anymore. Is it related to the recent hard fork update? How can I solve it?

Ps:
When I use the public node `https://api.elrond.com`, there is no method like `/hyperblock/by-nonce/123`, it will reported another error: `{"message":"Missing Authentication Token"}`, is there any other functions to use？

**Comment by miiu96** [comment]
1.   For your first question: can you provide more information like software version of your node, if is connected to the mainnet,  if you have logs please put in a comment to can take a look at what happened.

2. If you want to use API route` /hyberblock/by-nonce-123` instead of using 'https://api.elrond.com' please use 'https://gateway.elrond.com'

**Comment by miiu96** [comment]
Hello @Wangmmx. 
Did you figure out to solve your problems? 
Please let us know if we can close this issue.

**Comment by LucianMincu** [comment]
Hi @Wangmmx! 

Since we haven't heard from you in a while we consider this issue has been solved. 
Please feel free to reach out if you have any other issues. 

Thanks
