### ISSUE TITLE
[QUESTION] getTotalCumulatedRewards delegation manager

### ISSUE THREAD

**Issue by mihaieremia** [ElrondNetwork/elrond-go#2776]
Hey guys, I raised this question here after a conversation with @LucianMincu regarding the getTotalCumulatedRewards function.

Why is this function different than getClaimableRewards for example?
I tried to call it with my address as caller value but looks like is working just with this caller erd1qqqqqqqqqqqqqqqpqqqqqqqqlllllllllllllllllllllllllllsr9gav8. 
Should this function return the cumulated rewards per User or per agency SC?

Also would be great if we could have a function for agency SC which will return the total reward available/ever cumulated across the SC, not per user. Similar to getTotalActiveStake.

**Comment by LucianMincu** [comment]
Hi @mihaieremia. Seems like I got some more context about the `getTotalCumulatedRewards ` design. 

"Yields all the rewards received by the contract since it's creation.
This value is monotonously increasing - it can never decrease.
Handing out rewards will not decrease this value.
This is to keep track of how many funds entered the contract. It ignores any funds leaving the contract.
Individual rewards are computed based on this value."

`erd1qqqqqqqqqqqqqqqpqqqqqqqqlllllllllllllllllllllllllllsr9gav8` - end of epoch address

I do agree that getTotalCumulatedRewardsForUser would give a better overview for the users. 👍

**Comment by LucianMincu** [comment]
Hi @mihaieremia!

Your feature request got implemented and I'm happy to share with you that the view function is available in all delegation contracts on mainnet. 👍 

Thanks!
