### ISSUE TITLE
Problem CPU too high and can't sync

### ISSUE THREAD

**Issue by josefcoap** [ElrondNetwork/elrond-go#2901]
<details>
<summary>I fire up new observers in the same dedicated servers I usually use and same datacenter. The CPU load was crazy really, and seems not beeing able to sync</summary>
<pre>
AMD Ryzen 3700X
64GB 
512 NVM
Ubuntu 20.04.2
Kernel 5.4.0-66-generic
Mainnet node latest version 1.1.26.0
[elrond-node-0-0b24668f5ec8.zip](https://github.com/ElrondNetwork/elrond-go/files/6125497/elrond-node-0-0b24668f5ec8.zip)

</pre>
</details>

**Comment by raduchis** [comment]
I did take a look at the log, and it seems that the node last started at 19:40, it started synchronizing at around 19:42 and managed to synchronize from blocks 3217616 to 3217729, so more than 110 blocks, in 3 minutes. So the synchronization worked. The CPU load increases while synchronizing because it is able to process multiple blocks per round.

Am I looking at a wrong log? In the one from the description doesn't seem to be any problem.

**Comment by josefcoap** [comment]
Problem Solved Radu... I was running by error too much nodes there. Thanks mate
