### ISSUE TITLE
[FEAT] Flag to prevent node starting

### ISSUE THREAD

**Issue by lilok** [ElrondNetwork/elrond-go#2945]
Hello,

under some circumstance would be usefull to have a flag in elrond-nodes/node-*/config/prefs.toml to prevent a specific node from starting.

To prevent starting at boot it is possible to act via systemd but the script.sh start option starts all nodes.

Thanks

**Comment by iulianpascalau** [comment]
Interesting request. 
So the node binary should start (otherwise the daemon sub-system will try to start it continuously) but should enter in an endless loop. To start it you should modify the prefs.toml (remove the "sleeping" setting) and somehow restart that node. using the `./script.sh stop - ./script.sh start` will stop and start all nodes (not a great option to use). As an alternative you could kill the related pid (kind of risky if you are running multiple nodes on the same machine as you can easily kill the wrong pid)
