### ISSUE TITLE
could not create local data store: not supported cache type

### ISSUE THREAD

**Issue by joesixpack** [ElrondNetwork/elrond-go#313]
![image](https://user-images.githubusercontent.com/23145642/61998468-7bfeea80-b065-11e9-8d44-6c21a1860725.png)

**Comment by joesixpack** [comment]
[0800622e077f-2019-27-07-11-55-14.log](https://github.com/ElrondNetwork/elrond-go/files/3438491/0800622e077f-2019-27-07-11-55-14.log)

**Comment by iulianpascalau** [comment]
This happened due to a bad config file.

**Comment by LucianMincu** [comment]
Have managed to reproduced the error, and it happened because of the old config.toml file in the elrond-config/tags/v05 repository combined with the "Fix-bug-when-get-fom-storage-is-not-done" branch from elrond-go. 

Since the "Fix-bug-when-get-fom-storage-is-not-done" is a development branch and elrond-config is supposed to work only with the compatible public releases of "elrond-go".

A new public release will follow shortly in the elrond-config according with the public release of the elrond-go.
