### ISSUE TITLE
Issue: github.com\ElrondNetwork\elrond-sdk-erdgo\utils.go:19:30: undefined: keccak.Keccak

### ISSUE THREAD

**Issue by developertrt** [ElrondNetwork/elrond-go#3141]
<details>
<summary>Unresolved issue</summary>
<pre>
When I, Import `erdgo "github.com/ElrondNetwork/elrond-sdk-erdgo"`, Getting this kind of issue. How can I resolved it.
</pre>
</details>

**Comment by bogdan-rosianu** [comment]
Hi! Thank you for reporting this!

Where do you try to import the `erdgo`?  I was able to reproduce your issue only on `development` branch of `elrond-go`. In other branches of `elrond-go` or in another project it works. 

Your issue is caused because in the `development` there is a slight change regarding the hashers (they have a constructor and the structs are unexported) and go modules won't use the `elrond-go` from the `vendor` from within `elrond-sdk-erdgo`, and will use local elrond-go instead. 

Please try the `v1.0.0` release on other projects or in other branch of `elrond-go`.

Thank you!
