### ISSUE TITLE
[FEAT] keygenerator should be bundled within the Docker image

### ISSUE THREAD

**Issue by miohtama** [ElrondNetwork/elrond-go#3368]
To run a testnet node, one needs to generate a valid validator key as PEM file.

However, the binary `keygenerator` is not available in the Docker image, or the documentation lacks information how to get this binary to create your PEM file. No information is found on:

https://docs.elrond.com/validators/key-management/validator-keys/

https://docs.elrond.com/validators/testnet/use-docker-testnet/

https://docs.elrond.com/validators/testnet/config-scripts/

My suggestion is:

* Bundle `keygenerator` with Docker image

* Include an one line script that that generates the key to stdout, so that it can easily saved on the host system

* Include these instructions on Docker testnet node page https://docs.elrond.com/validators/testnet/use-docker-testnet/

Currently I did not find the `keygenerator` binary in the Docker image:

```
root@2a24d7acd40f:/go/elrond-go/cmd/node# ls
CLI.md  config  factory  flags.go  main.go  metrics  node
root@2a24d7acd40f:/go/elrond-go/cmd/node# ls -lha
total 66M
drwxr-xr-x 5 root root 4.0K Aug 19 14:17 .
drwxr-xr-x 3 root root 4.0K Aug 19 14:17 ..
-rw-r--r-- 1 root root 6.9K Aug 19 14:15 CLI.md
drwxr-xr-x 8 root root 4.0K Aug 19 14:17 config
drwxr-xr-x 2 root root 4.0K Aug 19 14:15 factory
-rw-r--r-- 1 root root  24K Aug 19 14:15 flags.go
-rw-r--r-- 1 root root 7.3K Aug 19 14:15 main.go
drwxr-xr-x 2 root root 4.0K Aug 19 14:15 metrics
-rwxr-xr-x 1 root root  66M Aug 19 14:17 node
root@2a24d7acd40f:/go/elrond-go/cmd/node# cd ..
root@2a24d7acd40f:/go/elrond-go/cmd# ls
node
root@2a24d7acd40f:/go/elrond-go/cmd# cd ..
root@2a24d7acd40f:/go/elrond-go# ls
cmd
root@2a24d7acd40f:/go/elrond-go# cd ..
root@2a24d7acd40f:/go# cd ..
root@2a24d7acd40f:/# find . -iname "keygenerator"
root@2a24d7acd40f:/# 

```

**Comment by gabi-vuls** [comment]
Hello miohtama!
Thank you for your suggestions.

We truly understand the discomfort , but  this process of building the validator key and wallet key was carefully studied and because of security reasons, the team decided that is more transparent and more safe for everyone to copy the keygenerator, take a look inside the code (and make sure that after the key is generated, it remains locally and is not sent to our servers or some other malicious third party) , compile it with your own hand and then the person can be 100% sure that he is the only one that have access to the key. 

We are constantly thinking about improvements for this process and we will come with a more "plug-and-play" solution in the near future. 

Thank you!
