### ISSUE TITLE
[Bug]: LKMEX to XMEX conversion tracker incorrect calculation

### ISSUE THREAD

**Issue by Cosminauh** [ElrondNetwork/elrond-go#4807]
### Contact Details

hyperc2k@gmail.com

### Description

LKMEX to XMEX conversion is not calculated correctly

### Steps to reproduce

LKMEX to XMEX conversion tracker performs incorrect calculation

Trx Hash ac6f55bb1a618478fd749c2d264e40de43ebc138bd69f21c22006405fcf752da

1. Unlock available LKMEX v1 (before conversion)
This was with "available now" as unlock deadline 14/12/2022

2. Now LKMEX to XMEX conversion tracker incorrectly calculated 99% converted
and not 100%.

"Available now" LXMEX is free of constraints at any point in time as the locking period has passed and the specific percentage is free.

"Available now" to be unlocked does not need to be taken into consideration especially before doing the conversion to XMEX.
This is completly unfair since LKMEX v1 "Available now" to be unlocked is a right already owned, before any conversion, before XMEX.
This ("Available now" unlock) should be a normal transaction belonging strictly to LKMEX v1 w/o any impact on XMEX.

Kindly fix this situation and repair the damage caused.

### On which network is the bug manifesting itself?

Mainnet

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ovidiuolteanu** [comment]
The paper is explicit in stating the following: 
- Unique bonus rewards will be granted to users who convert ALL their LKMEX
- A snapshot of LKMEX holders has already been taken just before this paper was published

Therefore, the entirety of LKMEX amount has to be converted, irrespective of how much it became available to unlock after the paper was published. More so, the user is prompted with a modal for consent that they may void the eligibility for these bonus rewards if they choose to unlock LKMEXv1 without migrating it.
Users that performed unlocks in the meantime but still want to reach the target quota have to lock additional MEX to total the snapshotted amount.

On a side note, this is the repo for "The official implementation of the Elrond protocol, written in golang", it doesn't have anything to do with the Exchange. For future assistance, please reach out to the telegram support groups or the exchange related repos, such as `sc-dex-rs`.

**Comment by Cosminauh** [comment]
Hi Ovidiu,

Thank you for the response.

I understad your point of view but placing conditions on an already earned right is immoral
no matter what the paper is explicit stating.

A paper is not a valid argument for doing something immoral for the investors.

Hope this makes sense.

Thanks,
Cosmin

**Comment by ovidiuolteanu** [comment]
User's earned right is not affected in any way. It is entirely user's option whether to unlock the unlockable MEX and do with it as he/she wills, or migrate it towards the new XMEX.
The only thing that changed is a new opportunity to access boosted metabonding rewards for a while in the new DEX format, but this is just an opportunity, not a given right. These boosted metabonding rewards are only accessible if the user **chooses** to migrate an equivalent amount of old LKMEX towards the new XMEX format, it in any way possible.
If the user chooses not to, he/she can still access unboosted metabonding rewards according to the new format based on how much energy he/she has on the account.

It is also important to note the fact that the change towards the new DEX format was subject to governance vote #1 which was passed with 88.16% approvals out of a 60.83% turnover rate. 
This renders issues of morality as invalid since all LKMEX holders had a chance to act on the aspects presented by the aforementioned paper and decide whether they accept the new terms or not.
