### ISSUE TITLE
p2plib strikes again. Sudden node crash on Linux

### ISSUE THREAD

**Issue by drdelphi** [ElrondNetwork/elrond-go#551]
[panic.tar.gz](https://github.com/ElrondNetwork/elrond-go/files/3733495/panic.tar.gz)

**Comment by drdelphi** [comment]
[panic2.tar.gz](https://github.com/ElrondNetwork/elrond-go/files/3736043/panic2.tar.gz)

**Comment by drdelphi** [comment]
[panic3.tar.gz](https://github.com/ElrondNetwork/elrond-go/files/3737481/panic3.tar.gz)

**Comment by iulianpascalau** [comment]
For first issue I suspect memory corruption as otherwise it is impossible to break that part of the code from pubsub.
For the second, I have opened an issue https://github.com/libp2p/go-buffer-pool/issues/11 . Also, this might be triggered by a memory corruption.
Third bug, `select` instruction failed. This definitely seems like a memory corruption.
