### ISSUE TITLE
v1.0.35 Part of consensus group while catching up to sync

### ISSUE THREAD

**Issue by koen84** [ElrondNetwork/elrond-go#585]
After the upgrade to v1.0.35 i was checking in on my node status a bit later and caught it being part of the consensus group while it still had a whole lot of syncing to do.  This seems quite wrong, because how can it validate on the blockchain when it doesn't have all the history yet ?

![Elrond-V35-syncing+consensus](https://user-images.githubusercontent.com/8461454/67496225-60af7580-f67c-11e9-8f73-2bacda54e819.png)

**Comment by koen84** [comment]
Can't attach the log because well over the 10 MB github limit.  Even when i can just upload this specific one.  We need a proper alternative if log submission is important.

**Comment by koen84** [comment]
Again, a double this time.
![Elrond-V35-syncing+consensus2](https://user-images.githubusercontent.com/8461454/67521210-b1d65e00-f6aa-11e9-8069-20579b2de1b7.png)

**Comment by iulianpascalau** [comment]
This happened because the node tried for a couple of times to get the required block and then it changed its highestProbableNonce to the last nonce it had (nonce=2699) and tried to propose/sign a new block with the next nonce (nonce = 2700). This is a protection fallback mechanism. If the network had indeed the block with nonce 13329, eventually the node will catch up and sync. Otherwise, a new majority will form and propose the block with nonce = 2700

**Comment by koen84** [comment]
Even if it already knows there's a much higher nonce available ?  And isn't the shard leader who "invites" the consensus members rather than a node itself "going off" like this ?

**Comment by iulianpascalau** [comment]
As stated, one node can only guess that the received header is correct if it can not follow the full block chain towards the received header. If it tries a couple of times to fetch the missing blocks and failed, it will revert to the highest block it has and enters into a "synchronized state". This is a non-issue.
