### ISSUE TITLE
Integration  with custom prometheus server

### ISSUE THREAD

**Issue by liuyangc3** [ElrondNetwork/elrond-go#597]
Dose Elrond support expose metrics that can be scaped into custom Prometheus server?

**Comment by bogdan-rosianu** [comment]
Hello.
We used prometheus for internal monitoring and it required an additional script in order to make it work. However, we found an alternative for it and prometheus it will probably be removed from our code.
As an alternative, you can use the _/node/status_ endpoint which will return a list of all the metrics we store. If you make a wrapper over it, you can use it in prometheus

**Comment by liuyangc3** [comment]
Thanks
