### ISSUE TITLE
Shard 3 die v1.0.38

### ISSUE THREAD

**Issue by longhuynh2811** [ElrondNetwork/elrond-go#657]
I can't sync or product block!
![image](https://user-images.githubusercontent.com/53088104/68530176-a20c7a00-0338-11ea-883f-00d8e93ce15c.png)
![image](https://user-images.githubusercontent.com/53088104/68530179-a5a00100-0338-11ea-8eaa-cb4a406578b6.png)

**Comment by BlockchainRevolutionOnline** [comment]
I restarted my Shard 1 node. But it cannot get into sync state since 12 hours now. It is always a few seconds behind. CPU and network side are relaxed. no bottleneck here.

One hour after restart the node:
![20191110__001](https://user-images.githubusercontent.com/49018350/68550816-c9ca1380-0406-11ea-8102-81f84409823f.png)

12 hours after restarting the node:  
![20191110__002](https://user-images.githubusercontent.com/49018350/68550837-039b1a00-0407-11ea-97cd-c6f10167e510.png)

https://testnet.elrond.com/#/address/97341c4f55bb388482f176fddaa0aec94370f4f1a7eea7f2cf6515139509d03f
No new transactions :-(

**Comment by iulianpascalau** [comment]
@longhuynh2811 v1.0.38 still had some sync/propose issues. They are fixed by now

**Comment by iulianpascalau** [comment]
@BlockchainRevolutionOnline there were some NTP sync issue at that time. They are now corrected by #640 by having multiple NTP sources.
