### ISSUE TITLE
Synchronization time remaining - no created block shard 4

### ISSUE THREAD

**Issue by Joinko** [ElrondNetwork/elrond-go#876]
My node syncs and then starts syncing - all the time
Consensus accepted and Blocks accepted are not added.
![Block](https://user-images.githubusercontent.com/57148469/71264902-5f7d8a80-2345-11ea-9aeb-f75fa840c22d.png)

**Comment by Joinko** [comment]
Last created block shard 4 - 20 min ago

**Comment by iulianpascalau** [comment]
The proposer/validator get rewards only if the block on which it signed upon will be committed successfully (the rest of the validators from the shard will get 0 rewards for that block). Since there were attacks on this testnet phase, some blocks might not have been successfully committed or even rollback as the shards struggle to advance their blockchain.
